#ifndef LEXICAL_H
#define LEXICAL_H

#include "expressions/expr.h"

// Different kinds of keywords
typedef enum {
    KW_ASSIGN, KW_IF, KW_ELSE, KW_WHILE, KW_ENDBLOCK, KW_RETURN, KW_PRINT
} e_keyword;

// Different kinds of tokens (variable, expression, keyword)
typedef enum {
    PT_VAR, PT_EXPR, PT_KEYWORD 
} e_prog_token_type;

// Content of a token (only one field is valid, depending on its token_type)
typedef union {
    e_keyword keyword;
    char var;
    t_expr_rpn expr_rpn;
} u_prog_token_content;

// Token generated by the lexer
typedef struct {
    e_prog_token_type token_type;
    u_prog_token_content content;
} t_prog_token;

void print_keyword(const e_keyword keyword); 
void print_prog_token(const t_prog_token *token);

void destroy_prog_token(t_prog_token *token);

#endif